openapi: 3.0.3
info:
  title: SyriusOrbit Map Schemas
  version: 1.0.0
paths: {}
components:
  schemas:
    mapLayer:
      type: string
      enum:
        - origin
        - mask
        - merged
      default: merged
    mapResource:
      type: object
      required:
        - layer
        - links
      properties:
        layer:
          $ref: '#/components/schemas/mapLayer'
        bbox:
          description: Bounding box of the map in minx,miny,maxx,maxy format.
          type: string
          example: -1.0,-2.0,3.4,5.6
        resolution:
          description: Size represented by one pixel.
          type: number
          minimum: 0
          example: 0.02
        contentType:
          type: string
          enum:
            - image/png
        links:
          type: array
          items:
            $ref: './schemas.common.yaml#/components/schemas/link'
